apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth-svc
    env: testing
spec:
  selector:
    app: auth-svc
    env: testing
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080