apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
    env: testing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        env: testing
    spec:
      containers:
      - name: gateway
        image: gateway
        imagePullPolicy: Never
        ports:
        - name: http-port
          containerPort: 8080
        env:
          - name: SERVER_PORT
            value: "8080"
          - name: SPRING_PROFILES_ACTIVE
            value: test
          - name: AUTH_SERVICE_URL
            value: http://auth-svc:8080
          - name: MOVIE_SERVICE_URL
            value: http://movie-svc:8080
          - name: MOVIE_APP_URL
            value: http://movie-app:8080
          - name: SPRING_ZIPKIN_BASE_URL
            value: http://zipkin:9411
